### ISSUE TITLE
Importing won't work

### ISSUE THREAD

**Issue by ayonix** [richsilv/meteor-semantic-ui-sass#1]
When I try to import it:

```
app.scss: Sass compiler error >> /Users/user/test/app.scss:1: error: file to import not found or unreadable: "packages/richsilv:semantic-ui-sass/assets/stylesheets/semantic-ui"
```

Packages:  

```
meteor-platform
insecure
accounts-password
accounts-ui
iron:router
coffeescript
houston:admin
richsilv:semantic-ui-sass
particle4dev:sass
```

app.scss

```
@import "packages/richsilv:semantic-ui-sass/assets/stylesheets/semantic-ui";
```

If I don't import it the syles aren't getting loaded.

How do I import/use it correctly?

**Comment by richsilv** [comment]
Thanks for catching this.  It's a problem with the way I was importing the
SCSS, but I'm getting some path reservation conflict errors when I try to
fix.  I'll have to sort this out tomorrow.

**Comment by richsilv** [comment]
Working directories have changed with the new build system, so we new have to specify a slightly unwieldy route relative to the .scss file that's doing the importing.  I've updated the README with how - hopefully a slightly more graceful solution will be made possible at some stage by MDG.
