### ISSUE TITLE
Remove richsilv:semantic-ui-sass from atmosphere?

### ISSUE THREAD

**Issue by splendido** [richsilv/meteor-semantic-ui-sass#3]
Hello @richsilv!

Do you agree it might be worth removing the package from atmosphere?
It's quite old and there's no official SASS version now.

See the 'Removing your package` section in the [Publishing](https://atmospherejs.com/i/publishing) page.
This is to keep our project folder as clean as possible and let new developers find good packages at the first attempt.

Thanks,
Luca

**Comment by splendido** [comment]
The same applies to [richsilv:semantic-ui](https://atmospherejs.com/richsilv/semantic-ui) for which the repository does not exist anymore.

We now have the official [semantic:ui-css](https://atmospherejs.com/semantic/ui-css)

**Comment by richsilv** [comment]
Yes, all agreed.  Both should now be removed.  Thanks for flagging!

**Comment by splendido** [comment]
Thanks, really appreciated!

Cheers
